src/Entity/PlatsPanier.php
<?php

namespace App\Entity;

use App\Entity\PlatsPanier;
use App\Repository\PlatsPanierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PlatsPanierRepository::class)
 */
class PlatsPanier
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantité;

    /**
     * @ORM\ManyToOne(targetEntity=PlatsPanier::class, inversedBy="plats")
     * @ORM\JoinColumn(nullable=false)
     */
    private $plats;

    /**
     * @ORM\ManyToOne(targetEntity=PlatsPanier::class, inversedBy="panier")
     * @ORM\JoinColumn(nullable=false)
     */
    private $panier;

    /**
     * @ORM\Column(type="float")
     */
    private $Price;

    public function __construct()
    {
        $this->plats = new ArrayCollection();
        $this->panier = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantité(): ?int
    {
        return $this->quantité;
    }

    public function setQuantité(int $quantité): self
    {
        $this->quantité = $quantité;

        return $this;
    }

    public function getPlats(): ?self
    {
        return $this->plats;
    }

    public function setPlats(?self $plats): self
    {
        $this->plats = $plats;

        return $this;
    }

    public function addPlat(self $plat): self
    {
        if (!$this->plats->contains($plat)) {
            $this->plats[] = $plat;
            $plat->setPlats($this);
        }

        return $this;
    }

    public function removePlat(self $plat): self
    {
        if ($this->plats->removeElement($plat)) {
            // set the owning side to null (unless already changed)
            if ($plat->getPlats() === $this) {
                $plat->setPlats(null);
            }
        }

        return $this;
    }

    public function getPanier(): ?self
    {
        return $this->panier;
    }

    public function setPanier(?self $panier): self
    {
        $this->panier = $panier;

        return $this;
    }

    public function addPanier(self $panier): self
    {
        if (!$this->panier->contains($panier)) {
            $this->panier[] = $panier;
            $panier->setPanier($this);
        }

        return $this;
    }

    public function removePanier(self $panier): self
    {
        if ($this->panier->removeElement($panier)) {
            // set the owning side to null (unless already changed)
            if ($panier->getPanier() === $this) {
                $panier->setPanier(null);
            }
        }

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }
}

src/Controller/AdminPanierController.php
<?php

namespace App\Controller;

use App\Entity\Panier;
use App\Form\PanierType;
use App\Repository\PanierRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

/**
 * @Route("/admin/panier")
 */
class AdminPanierController extends AbstractController
{
    /**
     * @Route("/", name="admin_panier_index", methods={"GET"})
     */
    public function index(SessionInterface $sessionInterface): Response
    {
        
        // 1. On récupère le panier s'il existe, sinon on en reprend un nouveau
        $cart = $sessionInterface->get('cart');
        if ($cart === null)
        {
             $cart = [
                'total' => 0.0,
                'elements' => []
            ];
        }

        return $this->render('admin_panier/index.html.twig', [
            'cart' => $cart,
        ]);
    }

    /**
     * @Route("/admin/panier/ajouter/{id}", name="admin_panier_add", methods={"GET"})
     */
    public function add(Panier $panier, SessionInterface $sessionInterface): Response
    {
        
        // 1. On récupère le panier s'il existe, sinon on en reprend un nouveau
        $cart = $sessionInterface->get('cart');
        if ($cart === null)
        {
             $cart = [
                'total' => 0.0,
                'elements' => []
                ];
        }

        // 2. On ajoute le plat s'il n'y en a pas
        $panierId = $panier->getId();
        if (!isset($cart['elements'][$panierId]))
        {
            $cart['elements'][$panierId] = [
                'panier' => $panier,
                'quantity' => 0
               ];   
        }

        // 3. On incrémente la quantity et on recalcul le prix total
        $cart['elements'][$panierId]['quantity'] = $cart['elements'][$panierId]['quantity'] + 1;
        $cart['total'] = $cart['total'] + $panier->getPrice();
        
        // 4. On sauvegarde le nouveau panier
        $sessionInterface->set('cart', $cart);

        // 5. On redirige l'utilisateur vers la page index du panier
        return $this->redirectToRoute('admin/panier_index');
        
    }
    /**
    * @Route("admin/panier/enlever/{id}", name="admin_panier_enlever")
    */
   public function delete(Book $book, SessionInterface $sessionInterface): Response
   {
       // 1. On récupère le panier s'il existe, sinon on en reprend un nouveau
        $cart = $sessionInterface->get('cart');
        if ($cart === null)
       {
           $cart = [
            'total' => 0.0,
            'elements' => []
            ];
       }

       
       // 2. Si le plat n'est pas dans le panier, on ne fait rien
       $panierId = $panier->getId();
       if (!isset($cart['elements'][$panierId]))
       {
           return $this->redirectToRoute('admin/panier_index');
       }


       // 3. Il existe, alors on met à jour les quantites
       $cart['total'] = $cart['total'] - $panier->getPrice();
       $cart['elements'][$panierId]['quantity'] = $cart['elements'][$panierId]['quantity'] - 1;


       // 4. Si la quantité est de 0, on l'enlève complétement du panier
       if ($cart['elements'][$panierId]['quantity'] <= 0)
       {
           unset($cart['elements'][$panierId]);
       }
       

       // 5. On sauvegarde le panier
       $sessionInterface->set('cart', $cart);

       // 6. On redirige l'utilisateur vers la page index du panier
       return $this->redirectToRoute('admin_panier_index');
   }

    
   // vider un panier 

   /**
    * @Route("admin/panier/vider", name="admin_panier_vider")
    */
   
   public function clear(SessionInterface $sessionInterface): Response
   {
        $sessionInterface->remove('cart');
        return $this->redirectToRoute('admin_panier_index');
   }

   /**
    * @Route("admin/panier/supprimer/{id}", name="admin_panier_supprimer")
    */

   public function removeLine(string $bookId, SessionInterface $sessionInterface): Response
   {
       $cart = $sessionInterface->get('cart');
       if ($cart === null)
       {
           $cart = [
               'total' => 0.0,
               'elements' => []
           ];
       }
       
       $panierId = $panier->getId();
       if (!isset($cart['elements'][$panierId]))
       {
           return $this->redirectToRoute('admin_panier_index');
       }

       $cart['total'] = $cart['total'] - $panier->getPrice() * $cart['elements'][$panierId]['quantity'];

       unset($cart['elements'][$panierId]);

       $sessionInterface->set('cart', $cart);

       return $this->redirectToRoute('admin_panier_index');
   }

   // Valider le panier
}
    

templates/admin_panier/_delete_form.html.twig
<form method="post" action="{{ path('admin_panier_delete', {'id': panier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ panier.id) }}">
    <button class="btn">Delete</button>
</form>

templates/admin_panier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Panier{% endblock %}

{% block body %}
    <h1>Edit Panier</h1>

    {{ include('admin_panier/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('admin_panier_index') }}">back to list</a>

    {{ include('admin_panier/_delete_form.html.twig') }}
{% endblock %}

templates/admin_panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier{% endblock %}

{% block body %}
<h1>Panier</h1>
<div>Total du panier {{ cart.total }} €</div>

<div>
    <a href="{{ path('admin_panier_vider') }}">Vider panier</a>
</div>
<table>
    <tr>
        <th>Nom</th>
        <th>Prix unitaire</th>
        <th>Quantité</th>
        <th>...</th>
    </tr>

    {% for element in cart.elements %}
        <tr>
            <td>{{ element.panier.plats}}</td>
            <td>{{ element.panier.price}}</td>
            <td>{{ element.panier.quantité}}</td>
            <td>
                <a href="{{ path('admin_panier_add', {'id': element.panier.id}) }}">+</a>
                <a href="{{ path('admin_panier_enlever', {'id': element.panier.id}) }}">-</a>
                <a href="{{ path('admin_panier_supprimer', {'id': element.panier.id}) }}">-</a>
            </td>          
        </tr>
    {% else %}
        <tr>
           <td colspan="4">Votre panier est vide</td> 
        </tr>
    {% endfor %}

</table>


    <a href="">Create new</a>
{% endblock %}

templates/admin_panier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Panier{% endblock %}

{% block body %}
    <h1>Create new Panier</h1>

    {{ include('admin_panier/_form.html.twig') }}

    <a href="{{ path('admin_panier_index') }}">back to list</a>
{% endblock %}

templates/admin_panier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier{% endblock %}

{% block body %}
    <h1>Panier</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ panier.id }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('admin_panier_index') }}">back to list</a>

    <a href="{{ path('admin_panier_edit', {'id': panier.id}) }}">edit</a>

    {{ include('admin_panier/_delete_form.html.twig') }}
{% endblock %}