src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $numero;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_cmde;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToOne(targetEntity=Panier::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $panier;

    /**
     * @ORM\OneToMany(targetEntity=CommandeDetail::class, mappedBy="commande")
     */
    private $commandeDetails;

    public function __construct()
    {
        $this->commandeDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getNumero(): ?int
    {
        return $this->numero;
    }

    public function setNumero(int $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getDateCmde(): ?\DateTimeInterface
    {
        return $this->date_cmde;
    }

    public function setDateCmde(\DateTimeInterface $date_cmde): self
    {
        $this->date_cmde = $date_cmde;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPanier(): ?Panier
    {
        return $this->panier;
    }

    public function setPanier(Panier $panier): self
    {
        $this->panier = $panier;

        return $this;
    }

    /**
     * @return Collection|CommandeDetail[]
     */
    public function getCommandeDetails(): Collection
    {
        return $this->commandeDetails;
    }

    public function addCommandeDetail(CommandeDetail $commandeDetail): self
    {
        if (!$this->commandeDetails->contains($commandeDetail)) {
            $this->commandeDetails[] = $commandeDetail;
            $commandeDetail->setCommande($this);
        }

        return $this;
    }

    public function removeCommandeDetail(CommandeDetail $commandeDetail): self
    {
        if ($this->commandeDetails->removeElement($commandeDetail)) {
            // set the owning side to null (unless already changed)
            if ($commandeDetail->getCommande() === $this) {
                $commandeDetail->setCommande(null);
            }
        }

        return $this;
    }
}

src/Controller/AdminCommandeController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Form\CommandeType;
use App\Repository\CommandeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/commande")
 */
class AdminCommandeController extends AbstractController
{
    /**
     * @Route("/", name="admin_commande_index", methods={"GET"})
     */
    public function index(CommandeRepository $commandeRepository): Response
    {
        return $this->render('admin_commande/index.html.twig', [
            'commandes' => $commandeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="admin_commande_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $commande = new Commande();
        $form = $this->createForm(CommandeType::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($commande);
            $entityManager->flush();

            return $this->redirectToRoute('admin_commande_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_commande/new.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="admin_commande_show", methods={"GET"})
     */
    public function show(Commande $commande): Response
    {
        return $this->render('admin_commande/show.html.twig', [
            'commande' => $commande,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_commande_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Commande $commande): Response
    {
        $form = $this->createForm(CommandeType::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_commande_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_commande/edit.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="admin_commande_delete", methods={"POST"})
     */
    public function delete(Request $request, Commande $commande): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commande->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($commande);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_commande_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_commande/_delete_form.html.twig
<form method="post" action="{{ path('admin_commande_delete', {'id': commande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
    <button class="btn">Delete</button>
</form>

templates/admin_commande/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commande{% endblock %}

{% block body %}
    <h1>Edit Commande</h1>

    {{ include('admin_commande/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('admin_commande_index') }}">back to list</a>

    {{ include('admin_commande/_delete_form.html.twig') }}
{% endblock %}

templates/admin_commande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande index{% endblock %}

{% block body %}
    <h1>Commande index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Price</th>
                <th>Numero</th>
                <th>Date_cmde</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
                <td>{{ commande.id }}</td>
                <td>{{ commande.price }}</td>
                <td>{{ commande.numero }}</td>
                <td>{{ commande.dateCmde ? commande.dateCmde|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('admin_commande_show', {'id': commande.id}) }}">show</a>
                    <a href="{{ path('admin_commande_edit', {'id': commande.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5"></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('admin_commande_new') }}">Create new</a>
{% endblock %}

templates/admin_commande/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commande{% endblock %}

{% block body %}
    <h1>Create new Commande</h1>

    {{ include('admin_commande/_form.html.twig') }}

    <a href="{{ path('admin_commande_index') }}">back to list</a>
{% endblock %}

templates/admin_commande/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
    <h1>Commande</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commande.id }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ commande.price }}</td>
            </tr>
            <tr>
                <th>Numero</th>
                <td>{{ commande.numero }}</td>
            </tr>
            <tr>
                <th>Date_cmde</th>
                <td>{{ commande.dateCmde ? commande.dateCmde|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('admin_commande_index') }}">back to list</a>

    <a href="{{ path('admin_commande_edit', {'id': commande.id}) }}">edit</a>

    {{ include('admin_commande/_delete_form.html.twig') }}
{% endblock %}